package:
    name: pyg-base
    version: 0.0.42

source:
    path: ../src
	
build:
    include_recipe: False
    number: 0
    noarch: python

requirements:
    build:
        - numpy             >=1.18.1
        - scipy             >=1.4.1
        - pandas            >=0.23.0
        - jsonpickle        >=1.2
        - pyg-npy           >=0.0.3
        
    run:
        - numpy             >=1.18.1
        - scipy             >=1.4.1
        - pandas            >=0.23.0
        - jsonpickle        >=1.2
        - pyg-npy           >=0.0.3
about:
    home: https://github.com/gityoav/pyg-base
    license: GNU