package:
    name: pyg-base
    version: 0.0.6

source:
    path: ../src
	
build:
    include_recipe: False
    number: 0
    noarch: python

requirements:
    build:
        - numpy             >=1.19.1
        - scipy             >=1.5.0
        - pandas            >=1.1.0
        - jsonpickle        >=1.2
        - fastparquet       >=0.4.1
    run:
        - numpy             >=1.19.1
        - scipy             >=1.5.0
        - pandas            >=1.1.0
        - jsonpickle        >=1.2
        - fastparquet       >=0.4.1
about:
    home: https://github.com/gityoav/pyg-base
    license: GNU